# Generated by Django 4.2.6 on 2023-10-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='last_update_date',
            new_name='updated_at',
        ),
    ]
